spring:
  application:
    name: UserService

  config:
    import: optional:configserver:http://config-server:8888

  rabbitmq:
    host: rabbitmq_container
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
#    hostname: localhost
    prefer-ip-address: true

logging:
  file:
    name: microservices_logs/UserService.log
  level:
    root: INFO
    org.springframework.web.client: DEBUG


keycloak:
  admin:
    username: user1
    password: User1@123
    server-url: http://keycloak:8080   # ✅ FIXED (was http://keycloak:8987)
    realm: E-Comm-Application
    client-id: admin-cli
    client-uid: 1dd75ae9-1e3f-4ab8-ac44-0284cc285fe7
    # client-secret: your-client-secret  # 🔥 Uncomment if client is confidential
          # ⚠️ IMPORTANT
# Optional but recommended (for debugging)
