spring:
  application:
    name: SpringCloud_EurekaServer

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    name: microservices_logs/SpringCloud_EurekaServer.log
  level:
    root: INFO
    org.springframework.web.client: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

